### ISSUE TITLE
Ran into problems with resetThenSet

### ISSUE THREAD

**Issue by ljsikuade** [dbilgili/Custom-ReactJS-Dropdown-Components#1]
Might just be me as I didn't fork this repo, but when I tried: 
  temp[id].selected = true;
I got an error saying that temp[id] was undefined on the last item of every list is used. 
I got around this quite easily though. Just replacing that line with: 
temp.find(item => item.id === id).selected = true;

As I could only think that it was an indexing issue of some kind.

**Comment by erBhushanPawar** [comment]
I think you need to change your setAndReset function code like this

`resetThenSet = (id, key) => {
        let temp = JSON.parse(JSON.stringify(this.state[key]));
        temp.map(item => item.id == id ? item.selected = true : item.selected = false);

        this.setState({
            [key]: temp
        });
    }
`
