### ISSUE TITLE
Extra scroll bar

### ISSUE THREAD

**Issue by aa-deet-eeya** [dbilgili/Custom-ReactJS-Dropdown-Components#23]
Open the [Online Demo](https://dbilgili.github.io/Custom-ReactJS-Dropdown-Components/index.html)
Click on Regular Drop Down menu expample, 
![issue1](https://user-images.githubusercontent.com/26107248/93777789-d207f780-fc42-11ea-98c4-fcb8c4f98fe8.png)
![issue2](https://user-images.githubusercontent.com/26107248/93777822-ddf3b980-fc42-11ea-9295-961aba04e2e8.png)

P.S : Removing the overflow from .dd-list should remove this, worked for me

**Comment by dbilgili** [comment]
Hey,
Thanks for pointing this out. Will fix it 👍🏻
