### ISSUE TITLE
Don't override global CSS please

### ISSUE THREAD

**Issue by molhanec** [dbilgili/Custom-ReactJS-Dropdown-Components#24]
The https://github.com/dbilgili/Custom-ReactJS-Dropdown-Components/blob/master/src/styles/base.sass
does set some global CSS affecting any project using this great lib.
Especially the
```
h3
  &:nth-of-type(2)
    margin-top: 50px
```
leaks.

**Comment by dbilgili** [comment]
Hey Michal,
Thanks for reporting this issue. It's now fixed and new version is released on NPM 👍🏻

**Comment by molhanec** [comment]
Wow, that was fast! Thanks!
