### ISSUE TITLE
Cannot read select values from variable

### ISSUE THREAD

**Issue by mikehenriquezf** [dbilgili/Custom-ReactJS-Dropdown-Components#28]
I have a profiles form that i need to edit sizes. Im passing the selected sizes in a variable and getting this result:

[{"value":"3.5"},{"value":"4"},{"value":"4.5"}]

If i just basically copy and paste that string into the component, it works:
select={[{"value":"3.5"},{"value":"4"},{"value":"4.5"}]}

But is not working if use it like this:
select={sizesToEdit}

**Comment by dbilgili** [comment]
Hey Mike,
Are you sure `sizesToEdit` has the correct array content?
Can you possibly provide an example in [codesandbox](https://codesandbox.io/)?

[Here](https://codesandbox.io/s/headless-microservice-9p074?file=/src/App.js) is an example where an array variable passed to `select` prop.

**Comment by mikehenriquezf** [comment]
Hello dbilgili,

Just put the example on codesandbox and is working as i expected, but i cannot make it work on my on-going project.

Here's my codesandbox example, i just need to change those sizes dynamically after selecting the desired profile, and edit them with the component.

https://codesandbox.io/s/testtest-qrdvf

**Comment by mikehenriquezf** [comment]
`sizesToEdit ` returns this:
[{"value":"3.5"},{"value":"4"},{"value":"4.5"}]

**Comment by mikehenriquezf** [comment]
Im passing the values to the state like this:

task.sizes.split('+').map((Number)=> {
    selectedSizes.push({value: Number})
})

**Comment by mikehenriquezf** [comment]
If i set the selectedValues hard-coded on the state, the select prop works, but if i update the state, the component dont work. Any idea?

**Comment by dbilgili** [comment]
> Im passing the values to the state like this:
> 
> task.sizes.split('+').map((Number)=> {
> selectedSizes.push({value: Number})
> })

You're mutating the state directly, instead of using `setState`, so React does not update the component.
You should do the following if you're using a class component.

```
const selectedSizes = task.sizes.split('+').map((Number) => ({ value: Number }));
this.setState({ selectedSizes });
```

And if you're using hooks:
```
const [selectedSizes, setSelectedSizes] = useState([]);
```

```
const selectedSizes = task.sizes.split('+').map((Number) => ({ value: Number }));
setSelectedSizes(selectedSizes)
```

**Comment by mikehenriquezf** [comment]
Thank you so much, it worked that way.

I was trying the same thing with the Dropdown component, and i was getting this error on codesandbox and in my project:
"Cannot read property 'label' of undefined"

I put a example here with the error im getting:
https://codesandbox.io/s/testtest-qrdvf

**Comment by mikehenriquezf** [comment]
<Dropdown
    name="region"
    title="Select Region"
    select={{ value: "FR" }}
    list={this.get_region_list()}
    onChange={this.onChange}
/>

is returning this error:
index.js:1 Uncaught TypeError: Cannot read property 'label' of undefined

**Comment by dbilgili** [comment]
It's because you're passing an array. You should only pass an object to `select` prop of `<Dropdown>` component, which is a single select dropdown.

See the **Selecting item(s) by default** section of the [README](https://github.com/dbilgili/Custom-ReactJS-Dropdown-Components#selecting-items-by-default).
