### ISSUE TITLE
Cannot read properties of null (reading 'selectAll') on DropdownMultiple

### ISSUE THREAD

**Issue by mikehenriquezf** [dbilgili/Custom-ReactJS-Dropdown-Components#30]
I'm getting `Cannot read properties of null (reading 'selectAll')` while trying to select all the items in my dropdown. Working example:
https://codesandbox.io/s/testtest-qrdvf?file=/src/App.js:51-67

**Comment by dbilgili** [comment]
This link does not reproduce the problem and it works fine. Can you share one where you reproduce the error?

**Comment by mikehenriquezf** [comment]
forgot to close the ticket, i just fixed it
