### ISSUE TITLE
Icon color change

### ISSUE THREAD

**Issue by ameer2468** [dbilgili/Custom-ReactJS-Dropdown-Components#31]
Hi, Is it not possible to change the color of the icon?

I did write styles={{checkIcon: color: 'white'}} and it isn't working. Even used fill.

**Comment by dbilgili** [comment]
Hey,
You need to target the `<path>` of the SVG.
Check out [this](https://codesandbox.io/s/react-image-crop-demo-with-react-hooks-forked-tvvt1?file=/src/App.js) example.

**Comment by ameer2468** [comment]
Thanks! It's just that im used to using Fontawesome :)
