### ISSUE TITLE
Face issue when selecting item - react-beautiful-dnd

### ISSUE THREAD

**Issue by mvinayakam** [dbilgili/Custom-ReactJS-Dropdown-Components#6]
Hello

I face the following error when i try and select a list item

react-beautiful-dnd An error has occurred while a drag is occurring.Any existing drag will be cancelled.> Uncaught Error: A cross-origin error was thrown.

**Comment by dbilgili** [comment]
Hey,
Looks like something is going wrong with another library you're using in the project, which is `react-beautiful-dnd`. How are you combining the dropdown menu with this drag&drop library?
